### PR TITLE
Feature/swappable stored upload

### PR DESCRIPTION
**Pull request by brianedelman**
This is a WIP and corresponds with issue #45 and uploading now for feedback/collaboration as I don't have time to get to it again until next week.
This allows for hot swapping the StoredUpload model. So far it's working great but if your swapped model, in my case LoanDocument has a non nullable field like a ForeignKey, then when StoredUpload gets created in api.py you get errors so still some issues to solve there.

Still to do:
Solve issue around non nullable fields on swapped models
Update documentation
New tests around models being swapped

### CODE REVIEW

**Comment by jcohen02** [comment]
Many thanks for this @brianedelman. Not sure how much time I'll have to take a look at this until next week either but I'll try and take a look at your TODOs.

**Comment by jcohen02** [comment]
Can I check where you expect users of the library to put their custom `StoredUpload` object parameters in this implementation? Is the intention that they extend `StoredUpload` within their own model definitions? I think I might be misunderstanding - I wasn't sure if the intention was that individuals can create their own named models that extend `BaseStoredUpload` or whether they have to use the name `StoredUpload`. Apologies for my confusion, I guess I probably need to go and take a look at the docs for the [swappable](https://github.com/wq/django-swappable-models) library! 🙂

**Comment by brianedelman** [comment]
hey @jcohen02 getting back to this today so hoping to solve remaining issues. Yeah the idea with swappable is that you can define your own model that extends from BaseStoredUpload and any time this project tries to use StoredUpload, we'll use either their model or our StoredUpload. It gets defined in the settings.py of the user's project like `DJANGO_DRF_FILEPOND_STOREDUPLOAD_MODEL = "loan.LoanDocument"`

**Comment by brianedelman** [comment]
Ok so after reviewing this more deeply the only way to solve the issue of my swapped model having a foreign key that is non nullable is to rewrite the functions found in api.py that actually create the StoredUpload. I was hoping I could figure out a way to swap things and then not have to rewrite those functions (since they aren't part of a class I can just hook into). But I can't see a cleaner solution at this point. I still think the swappable model idea could be a good improvement to this repo but it would need to come with the ability to redefine the points at which the object is created.

**Comment by jcohen02** [comment]
Thanks for your work on this @brianedelman and sorry to see it's not worked out as straightforwardly as hoped. It would certainly be good to include this sort of functionality in `django-drf-filepond` if a workable option can be found. I haven't yet had a chance to look at this but I'll see if I can do so in the next few days.

**Pull request closed without merging**
